=== DGCK81LNN/sandbox/xml-richard/richard.dtd
<!ELEMENT richard (volume*)>
<!ATTLIST richard xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml">

<!ELEMENT volume (title, (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*)>
<!ATTLIST volume id ID #REQUIRED>

<!ELEMENT title (#PCDATA|s)*>
<!ELEMENT p (#PCDATA|s)*>
<!ELEMENT h (#PCDATA|s)*>
<!ELEMENT i (#PCDATA|s)*>

<!ELEMENT b (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*>
<!ATTLIST b is (blockquote) #IMPLIED>
<!ATTLIST b lang CDATA #IMPLIED>
<!ATTLIST b class CDATA #IMPLIED>
<!ATTLIST b style CDATA #IMPLIED>

<!ELEMENT s (#PCDATA|s)*>
<!ATTLIST s is (b|i|u|em|strong|cite|s) #IMPLIED>
<!ATTLIST s lang CDATA #IMPLIED>
<!ATTLIST s class CDATA #IMPLIED>
<!ATTLIST s style CDATA #IMPLIED>

<!ELEMENT a EMPTY>
<!ATTLIST a js CDATA #IMPLIED>
<!ELEMENT js (#PCDATA)>

<!ELEMENT separator EMPTY>
<!ELEMENT pause EMPTY>
<!ELEMENT choose (choice*)>
<!ELEMENT choice (#PCDATA)>

<!ELEMENT if (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*>
<!ATTLIST if js CDATA #REQUIRED>
<!ELEMENT elif (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*>
<!ATTLIST elif js CDATA #REQUIRED>
<!ELEMENT else (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*>

<!ELEMENT case (when+)>
<!ELEMENT when (p|h|i|a|b|js|separator|pause|choose|(if, elif*, else?)|case|call)*>
<!ATTLIST when js CDATA #REQUIRED>

<!ELEMENT call EMPTY>
<!ATTLIST call target NMTOKEN #REQUIRED>

=== DGCK81LNN/sandbox/xml-richard/lwr.xml
<!DOCTYPE richard SYSTEM "richard.dtd">
<richard>
  <volume id="epidemic">
    <title><s lang="en">Love with Richard under Epidemic</s></title>

    <js>
      <![CDATA[
      while (data.epidemicRecord.length < 4) data.epidemicRecord.push(0)
      data.epidemicRecord.length = 4
      $.score = 0
      $.loveBonus = 100
                  + data.epidemicRecord[3] * 8
                  + data.epidemicRecord[2] * 6
                  + data.epidemicRecord[1] * 4
                  + data.epidemicRecord[0] * 2
      console.log({loveBonus})
      $.dScore = function (delta, isRaw) {
        if (!isRaw) delta *= loveBonus
        if (!Number.isInteger(delta))
          console.warn(`dScore(): 分值 ${delta} 不是整数，已取整为 ${delta | 0}`)
        delta |= 0
        score += delta
        outEl.appendChild(document.createElement("p"))
          .appendChild(document.createElement("i"))
          .textContent = `${delta < 0 ? delta : '+' + delta}, SCORE: ${$.score}`
      }
      ]]>
    </js>

    <!--00 - 故事背景 -->
    <p>经过两个多月的网课，疫情基本结束，学校终于要复课了。</p>
    <p>2020.4.20。复课的第一天，我满怀期待地走进了校门。熟悉的景象在我眼前展开，只是所有人都戴了个口罩。顶着大风，仿佛回到了二三月份。</p>
    <p>走在我前面的是我的8B班同学Richard。三个多月没看见他，他在我眼中更加高大了。我在网课时曾屡次想念过他，现在，我可以以学习为理由来接近他，和他在一起。</p>
    <p>我在上个学期观察过他，他很少和Sunny说话，Sunny也没有去主动找他。但我猜不出他是否已经放弃了Sunny。机不可失时不再来，我得在结课考之前追求到他。</p>
    <separator />

    <!--  01 - 重回校园 -->
    <a js="$.loveRush = false" />
    <p>我一边跟在他后面，一边思考要对他说什么。我和他按照老师的引导进入了七年八班的教室，也就是两年前我们上课的地方。</p>
    <p>他擦了自己的桌椅，然后拿出一本必背古诗文，趴在桌子上看。</p>
    <i>要对他说什么？</i>
    <choose>
      <choice>我有道题不会，你给我讲讲</choice>
      <choice>你好像不太高兴，怎么了</choice>
      <choice>我想和你一起复习</choice>
    </choose>
    <case>
      <when js="_ === 0">
        <a js="dScore(10)" />
        <p>我慢慢地向Richard走过去，带着一道我假装不会的题，向他提问：“我有一道数学题不会，这张卷子的第24题，你能给我讲一讲吗？”</p>
        <p>他似乎被吓了一下，抬起头来，惊讶地看着我。他接过了我手中的卷子，看了十几秒，然后开始给我讲。</p>
        <p>“先代值算出它的解析式，再把图像画出来，对P点的位置分三段讨论……”他讲得极为认真，似乎已经进入了他最为专心致志的境界。</p>
        <p>我有些搞不懂，他对我讲题为什么会这么认真，于是我准备问他一下，这时，他讲完了，又装作平静地对我说：“听明白了么？”</p>
        <p>我本来会这道题，但我回答了：“没有。”他又更加细致的讲了一遍，还把思路都告诉了我。这下，我对他更加崇拜与好奇了。</p>
        <p>他好暖啊。我好奇地问了他一下：“你为什么这么喜欢认真地给我讲题？”</p>
        <p>“我……就是喜欢帮助别人，不只是你。两年前，我就想给别人讲题，没有人来问我。现在，我更加珍惜给别人讲题的机会。”他在回答我时眼神在打转，似乎不敢长时间直视我，他有些害羞了。</p>
        <p>我仔细的想了一想，这种不好意思绝对是两年前Sunny给他留下的后遗症。这么一想，他应该幻想过给喜欢的人讲题。</p>
        <p>快上课了，我赶紧扭头走回了自己的座位。</p>
      </when>
      <when js="_ === 1">
        <a js="dScore(4)" />
        <p>我慢慢地向Richard走过去，对他说：“你好像有点不高兴，怎么了？”</p>
        <p>“没事，我没事。你去复习你的东西吧，别管我。”他抬头看了我一下，然后又低下头，拿起笔开始补作业。</p>
        <p>我有些失望，又问了他一下：“和我谈一谈你的心事行吗？我不会告诉别人。”</p>
        <p>“我没有什么心事，只是学习压力大。”他有些冷漠地回答了我。</p>
        <choose>
          <choice>靠近他，对他表白</choice>
          <choice>溜回自己的座位</choice>
        </choose>
        <case>
          <when js="_ === 0">
            <a js="loveRush = true"></a>
          </when>
          <when js="_ === 1">
            <p>我快速遛回了自己的座位，然后我趁他低头复习时偷偷回头看了看他。</p>
          </when>
        </case>
      </when>
      <when js="_ === 2">
        <a js="dScore(6)" />
        <p>我慢慢地向Richard走过去，对他说：“我想和你一起复习，行吗？”</p>
        <p>他惊讶地抬了起头，向我询问道：“你怎么了？没带卷子还是别的情况？”他的语气中带着一丝冷漠与低迷。</p>
        <choose>
          <choice>请求一起看古诗文小本</choice>
          <choice>不回答，并对他表白</choice>
          <choice>溜回自己的座位</choice>
        </choose>
        <case>
          <when js="_ === 0">
            <a js="dScore(2)" />
            <p>“没带古诗词小本。我能和你一起看么？”我为接近他，向他撒了个谎。</p>
            <p>“没问题，一起看吧。”他平平地说。</p>
            <p>我走了过去，蹲在他旁边假装在认真地背诵。我缓慢地挪动自己的身体，想要贴在他身上。</p>
            <p>他向左一挪，避开了我的小身躯，仍然目不转睛地盯着小本，完全没看我。他似乎又在思考什么。</p>
            <p>我不敢太张扬地追求，只好享受当下。和他靠的这么近，我感到自己快要融化了。过了一小会儿，我红着脸回了自己的座位。</p>
          </when>
          <when js="_ === 1">
            <a js="loveRush = true" />
          </when>
          <when js="_ === 2">
            <a js="dScore(-500, true)" />
            <p>“没事。”我小声的说，然后我快速遛回了自己的座位。我趁他低头复习时偷偷回头看了看他。</p>
          </when>
        </case>
      </when>
    </case>
    <if js="loveRush">
      <a js="dScore(-2400 + (0| 0.6 * (loveBonus - 100)), true)" />
      <p>我慢慢地走向他，然后弯下腰把头贴在他的耳边，表白的话已经到了嘴边。</p>
      <p>“我好喜欢你，Richard。”</p>
      <p>“你……你想对我干什么？”他有些不知所措，扭过头去背对着我：</p>
      <p>“我现在不想突然开始和女生交往。马上就要考试了，现在不是干这种事的时候。我还没复习呢。”他就这样拒绝了我。</p>
      <p>我又问了一下他：“你为什么不愿和我交往？我真的很喜欢你。”</p>
      <p>他叹了一口气，低声回答我：“哎——我已经失去一位挚爱了，经历过撕心裂肺的痛苦。我现在承受不起这种刺激。只要我不再和女生交往，就不会爱上，更不会再次经历痛苦的失去。</p>
      <p>“简单点来说，我就是患上了‘疫后综合征’：怀念疫前的日子，熬过着现在的生活，对未来失去希望。靠回忆度日，虽然平淡无聊，但也不会起大风浪。”</p>
      <p>我赶紧开导他：“我向你保证，我到死也不会离你远去。我肯定能实现你对恋爱的期待，治愈你的‘疫后综合征’。”</p>
      <p>他并没有回答我什么，只是一直盯着古诗文小本看。我能肯定他还在怀念和Sunny在一起的日子。</p>
      <p>我的强推战术失败了，可我还是不甘心。他居然对这么可爱的女孩子没有感觉。我有些失望地回了自己的座位。</p>
    </if>
    <separator />

    <!--  02 - 第一课 -->
    <a js="$.memory = false" />
    <p>第一节课被统一的广播占了，我感觉自己的心情明显不像网课时那么低落、无力。看着这熟悉又陌生的教室，我自然地回想起了初一时的事情。</p>
    <p>根据和Richard关系比较好的一个男生讲的，他在两年前的这个时候就已经靠近Sunny。那时我还完全在自己的小圈子里。</p>
    <p>直到18年的428春季运动会。那一天，他拿着一个神秘的“八班加油”，还不让大家看夹在里面的内容。他的哥们儿还对我说过：“那天早上，Sunny莫名其妙地坐在了他身边。”</p>
    <p>那天下午，他的事被几个女生揭开了。我的疑惑也解开了。自此之后，他开始疯狂地追求Sunny，但一直无果，持续了两三个月，然后他开始玩“暗示流”。每一次，他的言语都能逗笑我。</p>
    <p>关注“Sunny事件”后，我开始对他有了一丝兴趣。到了初二以后，他的学习成绩开始猛涨，甚至进了年级前十；而他变得更加内向了，只和固定的两三个男生说话。</p>
    <p>他这种怪异的性格更吸引了我的注意，但那时他似乎总是回忆着旧情而且排斥异性。我怕自己被他拒绝，就没能鼓起勇气与他交往。</p>
    <p>广播结束，下课了。他走出了教室的后门。我好奇地跟了出去。他在走廊里徘徊了一圈，然后进入了我们班曾经于此上课的小教室。</p>
    <i>跟着他进去吗？</i>
    <choose>
      <choice>跟着</choice>
      <choice>返回</choice>
    </choose>
    <case>
      <when js="_ === 0">
        <a js="dScore(5)" />
        <p>我走进了那个小教室，悄悄地小步靠近他。他正面对着一片画满涂鸦的墙，盯着看了一两分钟，然后把它拍了下来。</p>
        <p>我轻轻地问他：“Richard，你在看什么呢？”</p>
        <if js="loveRush">
          <p>他似乎被吓到了，立刻回了头，回答道：“墙上的字。”然后又入了迷地看了起来。</p>
          <p>他简短而严肃的回答让我心里一冷。刚才的表白起了巨大的‘负’作用，加剧了他对女生的排斥。</p>
          <p>他继续死盯着墙上的涂鸦，完全不想和我多说话。过了两三分钟，他转身就走，回了班。</p>
          <p>我看他走了，我也跟了出去。他回到了自己的座位，开始写起了物理卷子。</p>
        </if>
        <else>
          <p>他慢慢地转过身来，看着我说：“这里有我两年前留下的痕迹。看到这些东西，我就会想起那时候的事情，心里会畅快些。”</p>
          <p>我把与涂鸦墙的回忆分享给了他：“我还记得，七年级时咱们班里的柱子上全是字，被称作表白墙。我还在上面写过我的偶像呢。”</p>
          <choose>
            <choice>说说你的回忆</choice>
            <choice>一起回班吧</choice>
          </choose>
          <case>
            <when js="_ === 0">
              <a js="dScore(20)" />
              <a js="memory = true" />
              <p>我又问了一下他：“你都写过什么？说说你的回忆，我不会告诉别人。”</p>
              <p>“初一下学期，大概是两年前的稍早些时候，我在八班的表白墙上写过一个动漫人物的名字。我还记得原文字是‘表白Nadeko’。”</p>
              <p>我想知道他的更多往事，于是我柔柔地请求他：“我喜欢听你讲故事，哪怕虚构的也行。”</p>
              <p>“哎，这还是初一上学期的事。那个时候，大概是九月中上旬，我听到班里有人放清甜女声歌曲，还跟着舞蹈。《恋爱循环》这个歌名我后来才知道。</p>
              <p>“刚听到时，我还把它的前奏听成了<s lang="en">Side by Side</s>视频的片头旋律。运动会上，初一的女生跳了这个舞蹈，其中有我们班的几个小女生。</p>
              <p>“自此之后，我便没再听到这首歌。可是它的欢快旋律却挥之不去。期末考试那天的中午，我在五考场，出来时发现了三考场的异常动静。我这过去一看，便走上了一条‘不归路’。</p>
              <p>“有许多人围着看大屏幕上的鬼畜(恶搞)视频。我一下子听出了熟悉的旋律，再一看，这视频名叫‘8848太监循环’。我在这里又反复看了几遍才走开。</p>
              <p>“初一寒假，由于我的成绩不是很理想，又黑暗、又孤独、又颓废。我几乎每天都会听这些歌，无论时间、地点、我的心情。</p>
              <p>“初一下学期，我看了它所出自的动漫《化物语》。可能是因为每天都看，我对这歌曲中的女主有了一种特殊的喜欢，类似你们所说的追星或是偶像。”</p>
              <p>我一边听着，一边和他一起回忆着。也许，这就是一个内向男生的真实内心。身有万千情感回忆却不主动外露，只等一个有缘人来一同追忆回味。</p>
              <p>还有三分钟就上课了。他对我说：“我与《恋爱循环》这首歌的故事还有很多，它对我的影响至关重大，先讲这么多吧。”然后转头大步走出小教室。</p>
              <p>我并排地走在他身边，回了班。他回到了自己的座位，开始写起了物理卷子。</p>
            </when>
            <when js="_ === 1">
              <p>“咱们一起回班吧，我想看看你怎么做题。”</p>
              <p>他又呆呆地看了一会儿，然后转头大步走出小教室。我并排地走在他身边，回了自己班。他回到了自己的座位，开始写起了物理卷子。</p>
              <p>我在他身边看了几分钟。虽然我没有看明白他的思路，但他认真的样子确实让我着迷。</p>
            </when>
          </case>
        </else>
      </when>
      <when js="_ === 1">
        <p>我没有继续尾随他，返回了自己的座位。我看着重逢的同学们欢快如故，仿佛这疫情从未发生过一样。</p>
        <p>我等了许久，两分钟铃时，他才回来。</p>
      </when>
    </case>
    <separator />

    <!--  03 - 心理工作 -->
    <p>第四节课下课后，化学老师等了两分钟才放我们下去吃饭。Richard立刻就冲了出去。</p>
    <p>我顶着大风，走出了教学楼，却路遇年级组长设的分流卡口，堵了几分钟。历尽千辛万苦的防疫关，我终于来到了食堂二楼。</p>
    <p>当我打完饭，去寻找自己的座位时，Richard已经吃完了。在被老师“重兵把守”的食堂，我只能眼睁睁地看着他走远，不敢上前拉住他。</p>
    <p>开学第一天，我们如期刷了卷子讲了问题，但也意外连连。我所在的8B班却完美地避开了。</p>
    <p>第五节课时，楼道里传来大量脚步声。楼道西端的7B班突然紧急转移。下课后，听政治老师说的：他们的测温枪不准，一高一低，保险起见才转移至备用教室。</p>
    <p>紧接着，外面响起了做操的音乐，却没有老师引导我们下楼。8B班中做什么的都有。甚至有两人无视防疫要求，近距离对视了一会儿。</p>
    <p>他们俩的深情又一次激起了我对Richard的幻想：等到考试结束后或毕业后，我一定要和他独处一段时间，近距离的了解他。</p>
    <p>晚上，我写完了作业，看了看他的消息。他在朋友圈里发了小教室涂鸦墙和校园其他地方的照片，配着文字“览物之情，得无异乎”。</p>
    <p>结合他初一时的经历和涂鸦墙很久以前就有的事实。“得无异乎”应该是指他在初一和现在看到墙上涂鸦时心情迥然不同。</p>
    <if js="memory">
      <p>他和我讲初一的往事时，他的语气完全变了。他一定很怀念初一的生活，才会在讲述时那么走心，那么愿意和我分享，和我共同追忆。</p>
      <p>我的脑子中冒出了一个大胆的想法：我要尽量让他进入回忆的状态，这样我可以趁机卸下他防卫的外衣，治愈一直被他埋在心底的旧伤。</p>
      <p>这个计划也有一点小问题。就是我没有了解过他的内心，不知道哪里是他最留恋的地方。</p>
    </if>
    <separator />

    <!--  04 - 《神奇的水滴石》 -->
    <p>2020.4.23。我进班时，已经有一半的同学来了。Richard居然没有像前几天一样写古诗文小本，他在看手机。</p>
    <i>要怎么说？</i>
    <choose>
      <choice>赶紧复习！</choice>
      <choice>看什么呢，给我看看</choice>
      <choice>不去打扰他</choice>
    </choose>
    <case>
      <when js="_ === 0">
        <a js="dScore(3)" />
        <p>我向他走过去，对他说：“Richard，赶紧复习！”他的手机上显示的是密密麻麻的文字。</p>
        <p>他立刻收起了藏在课桌下的手机，开始写起卷子。他在写的时候，我回头看了看他的身姿。</p>
        <p>晚上八点多，Richard的好哥们儿Roy给我发了一个东西。他说这是Richard让他发的。</p>
        <p>发来的文件是Richard的小说《神奇的水滴石》，还有Richard附上的一句话：“你要是能读懂它的深层含义，明天可以来和我说一说。”</p>
      </when>
      <when js="_ === 1">
        <a js="dScore(10)" />
        <p>我向他走过去，对他说：“你在看什么呢？能给我看看么？”他的手机上显示的是密密麻麻的文字。</p>
        <p>“这是我准备在结课考后发布的小说。你要想看的话，今天放学后提前发给你。”说着，他的表情立刻不那么严肃了，他似乎已经不那么排斥我了。</p>
        <p>“你要是能读懂它的深层含义，明天可以来和我说一说。之前还没有像你这么主动的读者呢。”他补充道。</p>
        <p>下午回家后，我就开始看着手机焦急等待。到了晚上八点多，Richard才把他的小说《神奇的水滴石》发给了我。</p>
      </when>
      <when js="_ === 2">
        <p>我不想打扰他，就在自己的座位上回头看了一会他。他的手机上显示的是密密麻麻的文字。</p>
        <p>晚上八点多，Richard的好哥们儿Roy给我发了一个东西。他说这是Richard让他发的。</p>
        <p>发来的文件是Richard的小说《神奇的水滴石》，还有Richard附上的一句话：“你要是能读懂它的深层含义，明天可以来和我说一说。”</p>
      </when>
    </case>
    <p>刚开始读时，我觉得他写的有些难以理解，主角们的行为又似曾相识；但是，读到后半部分时，我却把自己读了进去。</p>
    <p>故事中，伊楠斯的性格和现实中的Richard几乎一模一样。茵苏因车祸而死对伊楠斯的沉重打击应该对应Sunny与他越走越远。而我的角色正是“长得和茵苏很像的梅古里”。</p>
    <p>在带入到故事中想一想，Richard应该已经期待一个长得像Sunny的人很久了，说不定他还暗中欣赏过我呢。</p>
